version: '3.6'

services:
  mysqldb:
    image: mysql:5.8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xmexico
    networks:
      - xmexico_net
    ports:
      - 3306:3306
