name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Update the dropplet
      uses: appleboy/scp-action@master
      env:
        HOST: ${{secrets.QA_SERVER_HOST}}
        USERNAME: ${{secrets.QA_SERVER_USERNAME}}
        PORT: ${{secrets.QA_SERVER_PORT}}
        KEY: ${{secrets.QA_SERVER_KEY}}
      with:
        source: "."
        target: "/app"

    - name: Build the container and run
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.QA_SERVER_HOST}}
        USERNAME: ${{secrets.SERVER_USERNAME}}
        PORT: ${{secrets.QA_SERVER_PORT}}
        KEY: ${{secrets.QA_SERVER_KEY}}
        script:  ./app/run.sh
